// <auto-generated />
namespace apiCrud.bo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class exclusaoCampoEscolaridadeSexo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exclusaoCampoEscolaridadeSexo));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011507154_exclusaoCampoEscolaridadeSexo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
